import Foundation

struct AppLanguageOption: Identifiable, Hashable {
    var id: String
    var englishName: String
    var nativeName: String

    static let russian = AppLanguageOption(id: "ru", englishName: "Russian", nativeName: "Русский")
    static let thai = AppLanguageOption(id: "th", englishName: "Thai", nativeName: "ไทย")
    static let english = AppLanguageOption(id: "en", englishName: "English", nativeName: "English")
    static let spanish = AppLanguageOption(id: "es", englishName: "Spanish", nativeName: "Español")
    static let german = AppLanguageOption(id: "de", englishName: "German", nativeName: "Deutsch")
    static let ukrainian = AppLanguageOption(id: "uk", englishName: "Ukrainian", nativeName: "Українська")
    static let polish = AppLanguageOption(id: "pl", englishName: "Polish", nativeName: "Polski")
    static let chinese = AppLanguageOption(id: "zh", englishName: "Chinese", nativeName: "中文")
    static let hindi = AppLanguageOption(id: "hi", englishName: "Hindi", nativeName: "हिन्दी")
    static let filipino = AppLanguageOption(id: "fil", englishName: "Filipino", nativeName: "Filipino")
    static let french = AppLanguageOption(id: "fr", englishName: "French", nativeName: "Français")

    static let supported: [AppLanguageOption] = [
        .russian,
        .thai,
        .english,
        .spanish,
        .german,
        .ukrainian,
        .polish,
        .chinese,
        .hindi,
        .filipino,
        .french
    ]
}

struct AppCopy {
    static let languageStorageKey = "knotlink.appLanguageCode"

    let language: AppLanguageOption

    init(languageCode: String) {
        language = AppLanguageOption.supported.first { $0.id == languageCode } ?? .english
    }

    static var current: AppCopy {
        AppCopy(languageCode: UserDefaults.standard.string(forKey: languageStorageKey) ?? AppLanguageOption.english.id)
    }

    func t(_ key: String) -> String {
        Self.translations[language.id]?[key] ?? Self.translations[AppLanguageOption.english.id]?[key] ?? key
    }

    func f(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: Locale(identifier: language.id), arguments: args)
    }

    func sectionTitle(_ section: AppSection) -> String {
        t(section.rawValue)
    }

    func settingsTabTitle(_ tab: String) -> String {
        t(tab)
    }

    func languageSavedMessage(appLanguage: String, translationLanguage: String, autoTranslate: Bool) -> String {
        autoTranslate ? f("languageSavedOn", appLanguage, translationLanguage) : f("languageSavedOff", appLanguage)
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "chats": "Chats",
            "contacts": "Contacts",
            "settings": "Settings",
            "profile": "Profile",
            "notifications": "Notifications",
            "languages": "Languages",
            "devices": "Devices",
            "settingsSubtitle": "Profile, notifications, language, and devices.",
            "username": "Username",
            "displayName": "Display Name",
            "email": "Email",
            "phone": "Phone",
            "notSet": "Not set",
            "passwordChangesUnavailable": "Password changes unavailable",
            "oauthPasswordUnavailable": "This workspace uses OAuth sign-in only. Password changes are not available from settings.",
            "logOut": "Log out",
            "enablePushNotifications": "Enable push notifications",
            "showMessagePreviews": "Show message previews",
            "notifyContactRequests": "Notify about contact requests",
            "notificationSound": "Notification Sound",
            "soundDefault": "Default",
            "soundSoftChime": "Soft chime",
            "soundClassicPing": "Classic ping",
            "soundSilent": "Silent",
            "saveNotificationSettings": "Save Notification Settings",
            "notificationSettingsSaved": "Notification settings saved.",
            "appLanguageTitle": "App Language",
            "appLanguageDetail": "Used for KnotLink screens, menus, and buttons.",
            "autoTranslationTitle": "Enable auto-translation",
            "translateToTitle": "Translate Messages To",
            "translateToDetail": "Incoming messages use this target language.",
            "saveLanguageSettings": "Save Language Settings",
            "languageSavedOn": "App language set to %@. Auto-translation to %@ is on.",
            "languageSavedOff": "App language set to %@. Auto-translation is off.",
            "thisDevice": "This Device",
            "activeNow": "Active now",
            "lastActiveJustNow": "Last active: Just now",
            "current": "Current",
            "saveDevicePreferences": "Save Device Preferences",
            "devicePreferencesSaved": "Device preferences saved.",
            "selectChat": "Select a chat",
            "conversationOpensHere": "Your conversation opens here.",
            "checkThis": "Check this",
            "updated": "Updated",
            "conversationsCount": "%d conversations",
            "searchChats": "Search Chats",
            "filter": "Filter",
            "allChats": "All Chats",
            "groups": "Groups",
            "bots": "Bots",
            "botChatsWillAppear": "Bot chats will appear here.",
            "noChatsFound": "No chats found.",
            "createGroup": "Create Group",
            "groupName": "Group name",
            "groupNamePlaceholder": "Weekend plans, Launch team...",
            "chooseMembers": "Choose members",
            "selectedMembersCount": "%d selected",
            "invitePeople": "Invite people",
            "allContactsInGroup": "All contacts are already in this group.",
            "contactsSubtitle": "Invite by phone, email, or nickname.",
            "contactLookupPlaceholder": "Phone, email, or @nickname",
            "incomingRequests": "Incoming requests",
            "yourContacts": "Your contacts",
            "noContactsYet": "No contacts yet.",
            "message": "Message",
            "sentInvitations": "Sent invitations",
            "pending": "Pending",
            "accept": "Accept",
            "decline": "Decline",
            "profileSubtitle": "Manage your public identity.",
            "profilePhoto": "Profile photo",
            "changeProfilePhoto": "Change",
            "viewProfilePhoto": "View",
            "profilePhotoUpdated": "Profile photo updated.",
            "profilePhotoUpdateFailed": "Could not update profile photo.",
            "firstName": "First name",
            "lastName": "Last name",
            "saveProfile": "Save profile",
            "memberSince": "Member since",
            "authSignupSubtitle": "Create your account with email or Google.",
            "authLoginSubtitle": "Sign in with email or Google.",
            "continueWithGoogle": "Continue with Google",
            "continueWithMailRu": "Continue with Mail.ru",
            "or": "or",
            "authenticationMode": "Authentication mode",
            "login": "Log in",
            "register": "Register",
            "createAccount": "Create account",
            "password": "Password",
            "confirmPassword": "Confirm password",
            "back": "Back",
            "search": "Search",
            "cancel": "Cancel",
            "close": "Close",
            "chatInfo": "Chat Info",
            "contactInfo": "Contact Info",
            "links": "Links",
            "translateChat": "Translate",
            "stopTranslation": "Stop Translation",
            "translationEnabledForChat": "Translation to %@ is on.",
            "translationDisabledForChat": "Translation is off.",
            "clearHistory": "Clear History",
            "deleteChat": "Delete Chat",
            "attachmentsReady": "Attachments are ready for backend wiring.",
            "addAttachment": "Add attachment",
            "editPhoto": "Edit Photo",
            "addText": "Add text",
            "done": "Done",
            "crop": "Crop",
            "text": "Text",
            "tune": "Tune",
            "photosAndVideos": "Photos & Videos",
            "photosAndVideosDetail": "Choose media from your library.",
            "files": "Files",
            "filesDetail": "Attach documents and files.",
            "photoAttachment": "Photo",
            "videoAttachment": "Video",
            "fileAttachment": "File",
            "attachmentPrefix": "Attachment",
            "attachmentsAdded": "%d attachment(s) added.",
            "fileImportFailed": "Could not add that file.",
            "removeAttachment": "Remove attachment",
            "participants": "%d participants",
            "members": "Members",
            "linksAndDocs": "Links and docs",
            "noSharedLinksYet": "No shared links yet.",
            "loginSuccessful": "Login successful.",
            "googleSignInFailed": "Google sign-in failed.",
            "mailRuSignInFailed": "Mail.ru login failed. Please try again.",
            "enterValidEmail": "Enter a valid email address.",
            "passwordMin": "Password must be at least 8 characters.",
            "displayNameMin": "Display name must be at least 2 characters.",
            "usernameInvalid": "Username can use letters, numbers, and underscores only.",
            "enterValidPhone": "Enter a valid phone number.",
            "passwordsNoMatch": "Passwords do not match.",
            "accountCreatedEmailVerification": "Account created. Email verification is ready to connect to the backend.",
            "messageCannotBeEmpty": "Message cannot be empty.",
            "messageTooLong": "Message is too long. Keep it under 2000 characters.",
            "enterContactLookup": "Enter a phone number, email, or @nickname.",
            "noUserFound": "No user found with that phone, email, or nickname.",
            "invitationSent": "Invitation sent to %@.",
            "invitationAccepted": "Invitation accepted. You can now chat with this contact.",
            "invitationDeclined": "Invitation declined.",
            "chatHistoryDeleted": "Chat history deleted.",
            "chatDeleted": "Chat deleted.",
            "profileUpdated": "Profile updated.",
            "enterGroupName": "Enter a group name.",
            "selectAtLeastOneGroupMember": "Select at least one contact for the group.",
            "groupCreated": "Group created.",
            "addedToGroup": "%@ added to the group.",
            "addedPeopleToGroup": "%d people added to the group."
        ],
        "es": [
            "chats": "Chats",
            "contacts": "Contactos",
            "settings": "Ajustes",
            "profile": "Perfil",
            "notifications": "Notificaciones",
            "languages": "Idiomas",
            "devices": "Dispositivos",
            "settingsSubtitle": "Perfil, notificaciones, idioma y dispositivos.",
            "username": "Nombre de usuario",
            "displayName": "Nombre visible",
            "email": "Correo electrónico",
            "phone": "Teléfono",
            "notSet": "No configurado",
            "passwordChangesUnavailable": "Cambios de contraseña no disponibles",
            "oauthPasswordUnavailable": "Este espacio usa solo inicio de sesión con OAuth. Los cambios de contraseña no están disponibles en ajustes.",
            "logOut": "Cerrar sesión",
            "enablePushNotifications": "Activar notificaciones push",
            "showMessagePreviews": "Mostrar vistas previas de mensajes",
            "notifyContactRequests": "Notificar solicitudes de contacto",
            "notificationSound": "Sonido de notificación",
            "soundDefault": "Predeterminado",
            "soundSoftChime": "Campanilla suave",
            "soundClassicPing": "Ping clásico",
            "soundSilent": "Silencio",
            "saveNotificationSettings": "Guardar notificaciones",
            "notificationSettingsSaved": "Ajustes de notificaciones guardados.",
            "appLanguageTitle": "Idioma de la app",
            "appLanguageDetail": "Se usa en pantallas, menús y botones de KnotLink.",
            "autoTranslationTitle": "Activar traducción automática",
            "translateToTitle": "Traducir mensajes a",
            "translateToDetail": "Los mensajes entrantes usan este idioma de destino.",
            "saveLanguageSettings": "Guardar idioma",
            "languageSavedOn": "Idioma de la app establecido en %@. La traducción automática a %@ está activada.",
            "languageSavedOff": "Idioma de la app establecido en %@. La traducción automática está desactivada.",
            "thisDevice": "Este dispositivo",
            "activeNow": "Activo ahora",
            "lastActiveJustNow": "Última actividad: ahora",
            "current": "Actual",
            "saveDevicePreferences": "Guardar preferencias del dispositivo",
            "devicePreferencesSaved": "Preferencias del dispositivo guardadas.",
            "selectChat": "Selecciona un chat",
            "conversationOpensHere": "Tu conversación se abrirá aquí.",
            "checkThis": "Mira esto",
            "updated": "Actualizado",
            "conversationsCount": "%d conversaciones",
            "searchChats": "Buscar chats",
            "filter": "Filtro",
            "allChats": "Todos los chats",
            "groups": "Grupos",
            "bots": "Bots",
            "botChatsWillAppear": "Los chats de bots aparecerán aquí.",
            "noChatsFound": "No se encontraron chats.",
            "createGroup": "Crear grupo",
            "groupName": "Nombre del grupo",
            "groupNamePlaceholder": "Planes del fin de semana, equipo de lanzamiento...",
            "chooseMembers": "Elegir miembros",
            "selectedMembersCount": "%d seleccionados",
            "invitePeople": "Invitar personas",
            "allContactsInGroup": "Todos los contactos ya están en este grupo.",
            "contactsSubtitle": "Invita por teléfono, correo o apodo.",
            "contactLookupPlaceholder": "Teléfono, correo o @apodo",
            "incomingRequests": "Solicitudes recibidas",
            "yourContacts": "Tus contactos",
            "noContactsYet": "Aún no hay contactos.",
            "message": "Mensaje",
            "sentInvitations": "Invitaciones enviadas",
            "pending": "Pendiente",
            "accept": "Aceptar",
            "decline": "Rechazar",
            "profileSubtitle": "Gestiona tu identidad pública.",
            "profilePhoto": "Foto de perfil",
            "changeProfilePhoto": "Cambiar",
            "viewProfilePhoto": "Ver",
            "profilePhotoUpdated": "Foto de perfil actualizada.",
            "profilePhotoUpdateFailed": "No se pudo actualizar la foto de perfil.",
            "firstName": "Nombre",
            "lastName": "Apellido",
            "saveProfile": "Guardar perfil",
            "memberSince": "Miembro desde",
            "authSignupSubtitle": "Crea tu cuenta con correo o Google.",
            "authLoginSubtitle": "Inicia sesión con correo o Google.",
            "continueWithGoogle": "Continuar con Google",
            "or": "o",
            "authenticationMode": "Modo de autenticación",
            "login": "Iniciar sesión",
            "register": "Registrarse",
            "createAccount": "Crear cuenta",
            "password": "Contraseña",
            "confirmPassword": "Confirmar contraseña",
            "back": "Atrás",
            "search": "Buscar",
            "cancel": "Cancelar",
            "close": "Cerrar",
            "chatInfo": "Información del chat",
            "contactInfo": "Información del contacto",
            "links": "Enlaces",
            "translateChat": "Traducir",
            "stopTranslation": "Detener traducción",
            "translationEnabledForChat": "La traducción a %@ está activada.",
            "translationDisabledForChat": "La traducción está desactivada.",
            "clearHistory": "Borrar historial",
            "deleteChat": "Eliminar chat",
            "attachmentsReady": "Los adjuntos están listos para conectar con el backend.",
            "addAttachment": "Añadir adjunto",
            "editPhoto": "Editar foto",
            "addText": "Añadir texto",
            "done": "Listo",
            "crop": "Recortar",
            "text": "Texto",
            "tune": "Ajustar",
            "photosAndVideos": "Fotos y videos",
            "photosAndVideosDetail": "Elige medios de tu biblioteca.",
            "files": "Archivos",
            "filesDetail": "Adjunta documentos y archivos.",
            "photoAttachment": "Foto",
            "videoAttachment": "Video",
            "fileAttachment": "Archivo",
            "attachmentPrefix": "Adjunto",
            "attachmentsAdded": "%d adjunto(s) añadidos.",
            "fileImportFailed": "No se pudo añadir ese archivo.",
            "removeAttachment": "Quitar adjunto",
            "participants": "%d participantes",
            "members": "Miembros",
            "linksAndDocs": "Enlaces y documentos",
            "noSharedLinksYet": "Aún no hay enlaces compartidos.",
            "loginSuccessful": "Inicio de sesión correcto.",
            "googleSignInFailed": "Error al iniciar sesión con Google.",
            "enterValidEmail": "Introduce un correo electrónico válido.",
            "passwordMin": "La contraseña debe tener al menos 8 caracteres.",
            "displayNameMin": "El nombre visible debe tener al menos 2 caracteres.",
            "usernameInvalid": "El nombre de usuario solo puede usar letras, números y guiones bajos.",
            "enterValidPhone": "Introduce un número de teléfono válido.",
            "passwordsNoMatch": "Las contraseñas no coinciden.",
            "accountCreatedEmailVerification": "Cuenta creada. La verificación por correo está lista para conectarse al backend.",
            "messageCannotBeEmpty": "El mensaje no puede estar vacío.",
            "messageTooLong": "El mensaje es demasiado largo. Manténlo por debajo de 2000 caracteres.",
            "enterContactLookup": "Introduce un teléfono, correo o @apodo.",
            "noUserFound": "No se encontró ningún usuario con ese teléfono, correo o apodo.",
            "invitationSent": "Invitación enviada a %@.",
            "invitationAccepted": "Invitación aceptada. Ya puedes chatear con este contacto.",
            "invitationDeclined": "Invitación rechazada.",
            "chatHistoryDeleted": "Historial del chat borrado.",
            "chatDeleted": "Chat eliminado.",
            "profileUpdated": "Perfil actualizado.",
            "enterGroupName": "Introduce un nombre de grupo.",
            "selectAtLeastOneGroupMember": "Selecciona al menos un contacto para el grupo.",
            "groupCreated": "Grupo creado.",
            "addedToGroup": "%@ añadido al grupo.",
            "addedPeopleToGroup": "%d personas añadidas al grupo."
        ],
        "ru": [
            "chats": "Чаты",
            "contacts": "Контакты",
            "settings": "Настройки",
            "profile": "Профиль",
            "notifications": "Уведомления",
            "languages": "Языки",
            "devices": "Устройства",
            "settingsSubtitle": "Профиль, уведомления, язык и устройства.",
            "username": "Имя пользователя",
            "displayName": "Отображаемое имя",
            "email": "Эл. почта",
            "phone": "Телефон",
            "notSet": "Не задано",
            "passwordChangesUnavailable": "Смена пароля недоступна",
            "oauthPasswordUnavailable": "В этом рабочем пространстве вход только через OAuth. Смена пароля недоступна в настройках.",
            "logOut": "Выйти",
            "enablePushNotifications": "Включить push-уведомления",
            "showMessagePreviews": "Показывать предпросмотр сообщений",
            "notifyContactRequests": "Уведомлять о запросах контактов",
            "notificationSound": "Звук уведомлений",
            "soundDefault": "По умолчанию",
            "soundSoftChime": "Мягкий звонок",
            "soundClassicPing": "Классический сигнал",
            "soundSilent": "Без звука",
            "saveNotificationSettings": "Сохранить настройки уведомлений",
            "notificationSettingsSaved": "Настройки уведомлений сохранены.",
            "appLanguageTitle": "Язык приложения",
            "appLanguageDetail": "Используется для экранов, меню и кнопок KnotLink.",
            "autoTranslationTitle": "Включить автоперевод",
            "translateToTitle": "Переводить сообщения на",
            "translateToDetail": "Входящие сообщения будут использовать этот язык.",
            "saveLanguageSettings": "Сохранить настройки языка",
            "languageSavedOn": "Язык приложения: %@. Автоперевод на %@ включен.",
            "languageSavedOff": "Язык приложения: %@. Автоперевод выключен.",
            "thisDevice": "Это устройство",
            "activeNow": "Активно сейчас",
            "lastActiveJustNow": "Последняя активность: сейчас",
            "current": "Текущее",
            "saveDevicePreferences": "Сохранить настройки устройства",
            "devicePreferencesSaved": "Настройки устройства сохранены.",
            "selectChat": "Выберите чат",
            "conversationOpensHere": "Здесь откроется переписка.",
            "checkThis": "Проверьте",
            "updated": "Обновлено",
            "conversationsCount": "%d переписок",
            "searchChats": "Поиск чатов",
            "filter": "Фильтр",
            "allChats": "Все чаты",
            "groups": "Группы",
            "bots": "Боты",
            "botChatsWillAppear": "Здесь появятся чаты с ботами.",
            "noChatsFound": "Чаты не найдены.",
            "createGroup": "Создать группу",
            "groupName": "Название группы",
            "groupNamePlaceholder": "Планы на выходные, Команда запуска...",
            "chooseMembers": "Выберите участников",
            "selectedMembersCount": "%d выбрано",
            "invitePeople": "Пригласить людей",
            "allContactsInGroup": "Все контакты уже в этой группе.",
            "contactsSubtitle": "Приглашайте по телефону, почте или нику.",
            "contactLookupPlaceholder": "Телефон, почта или @ник",
            "incomingRequests": "Входящие запросы",
            "yourContacts": "Ваши контакты",
            "noContactsYet": "Контактов пока нет.",
            "message": "Сообщение",
            "sentInvitations": "Отправленные приглашения",
            "pending": "Ожидает",
            "accept": "Принять",
            "decline": "Отклонить",
            "profileSubtitle": "Управляйте публичным профилем.",
            "firstName": "Имя",
            "lastName": "Фамилия",
            "saveProfile": "Сохранить профиль",
            "memberSince": "Участник с",
            "authSignupSubtitle": "Создайте аккаунт через почту или Google.",
            "authLoginSubtitle": "Войдите через почту или Google.",
            "continueWithGoogle": "Продолжить с Google",
            "or": "или",
            "authenticationMode": "Режим входа",
            "login": "Войти",
            "register": "Регистрация",
            "createAccount": "Создать аккаунт",
            "password": "Пароль",
            "confirmPassword": "Подтвердите пароль",
            "back": "Назад",
            "search": "Поиск",
            "cancel": "Отмена",
            "chatInfo": "Информация о чате",
            "contactInfo": "Информация о контакте",
            "links": "Ссылки",
            "translateChat": "Перевести",
            "stopTranslation": "Остановить перевод",
            "translationEnabledForChat": "Перевод на %@ включен.",
            "translationDisabledForChat": "Перевод выключен.",
            "clearHistory": "Очистить историю",
            "deleteChat": "Удалить чат",
            "attachmentsReady": "Вложения готовы к подключению бэкенда.",
            "addAttachment": "Добавить вложение",
            "editPhoto": "Редактировать фото",
            "addText": "Добавить текст",
            "done": "Готово",
            "crop": "Кадрировать",
            "text": "Текст",
            "tune": "Настроить",
            "photosAndVideos": "Фото и видео",
            "photosAndVideosDetail": "Выберите медиа из библиотеки.",
            "files": "Файлы",
            "filesDetail": "Прикрепите документы и файлы.",
            "photoAttachment": "Фото",
            "videoAttachment": "Видео",
            "fileAttachment": "Файл",
            "attachmentPrefix": "Вложение",
            "attachmentsAdded": "Добавлено вложений: %d.",
            "fileImportFailed": "Не удалось добавить файл.",
            "removeAttachment": "Удалить вложение",
            "participants": "%d участников",
            "members": "Участники",
            "linksAndDocs": "Ссылки и документы",
            "noSharedLinksYet": "Общих ссылок пока нет.",
            "loginSuccessful": "Вход выполнен.",
            "googleSignInFailed": "Вход через Google не удался.",
            "enterValidEmail": "Введите корректный адрес эл. почты.",
            "passwordMin": "Пароль должен быть не короче 8 символов.",
            "displayNameMin": "Отображаемое имя должно быть не короче 2 символов.",
            "usernameInvalid": "Имя пользователя может содержать только буквы, цифры и подчеркивания.",
            "enterValidPhone": "Введите корректный номер телефона.",
            "passwordsNoMatch": "Пароли не совпадают.",
            "accountCreatedEmailVerification": "Аккаунт создан. Проверка почты готова к подключению к бэкенду.",
            "messageCannotBeEmpty": "Сообщение не может быть пустым.",
            "messageTooLong": "Сообщение слишком длинное. Не более 2000 символов.",
            "enterContactLookup": "Введите телефон, почту или @ник.",
            "noUserFound": "Пользователь с таким телефоном, почтой или ником не найден.",
            "invitationSent": "Приглашение отправлено: %@.",
            "invitationAccepted": "Приглашение принято. Теперь можно писать этому контакту.",
            "invitationDeclined": "Приглашение отклонено.",
            "chatHistoryDeleted": "История чата удалена.",
            "chatDeleted": "Чат удален.",
            "profileUpdated": "Профиль обновлен.",
            "enterGroupName": "Введите название группы.",
            "selectAtLeastOneGroupMember": "Выберите хотя бы один контакт для группы.",
            "groupCreated": "Группа создана.",
            "addedToGroup": "%@ добавлен(а) в группу.",
            "addedPeopleToGroup": "Добавлено участников: %d."
        ],
        "de": [
            "chats": "Chats",
            "contacts": "Kontakte",
            "settings": "Einstellungen",
            "profile": "Profil",
            "notifications": "Mitteilungen",
            "languages": "Sprachen",
            "devices": "Geräte",
            "settingsSubtitle": "Profil, Mitteilungen, Sprache und Geräte.",
            "username": "Benutzername",
            "displayName": "Anzeigename",
            "email": "E-Mail",
            "phone": "Telefon",
            "notSet": "Nicht festgelegt",
            "passwordChangesUnavailable": "Passwortänderungen nicht verfügbar",
            "oauthPasswordUnavailable": "Dieser Arbeitsbereich nutzt nur OAuth-Anmeldung. Passwortänderungen sind in den Einstellungen nicht verfügbar.",
            "logOut": "Abmelden",
            "enablePushNotifications": "Push-Mitteilungen aktivieren",
            "showMessagePreviews": "Nachrichtenvorschau anzeigen",
            "notifyContactRequests": "Über Kontaktanfragen benachrichtigen",
            "notificationSound": "Mitteilungston",
            "soundDefault": "Standard",
            "soundSoftChime": "Sanfter Klang",
            "soundClassicPing": "Klassischer Ping",
            "soundSilent": "Stumm",
            "saveNotificationSettings": "Mitteilungseinstellungen speichern",
            "notificationSettingsSaved": "Mitteilungseinstellungen gespeichert.",
            "appLanguageTitle": "App-Sprache",
            "appLanguageDetail": "Wird für KnotLink-Bildschirme, Menüs und Buttons verwendet.",
            "autoTranslationTitle": "Automatische Übersetzung aktivieren",
            "translateToTitle": "Nachrichten übersetzen in",
            "translateToDetail": "Eingehende Nachrichten verwenden diese Zielsprache.",
            "saveLanguageSettings": "Spracheinstellungen speichern",
            "languageSavedOn": "App-Sprache auf %@ gesetzt. Automatische Übersetzung nach %@ ist aktiv.",
            "languageSavedOff": "App-Sprache auf %@ gesetzt. Automatische Übersetzung ist deaktiviert.",
            "thisDevice": "Dieses Gerät",
            "activeNow": "Jetzt aktiv",
            "lastActiveJustNow": "Zuletzt aktiv: gerade eben",
            "current": "Aktuell",
            "saveDevicePreferences": "Geräteeinstellungen speichern",
            "devicePreferencesSaved": "Geräteeinstellungen gespeichert.",
            "selectChat": "Chat auswählen",
            "conversationOpensHere": "Deine Unterhaltung wird hier geöffnet.",
            "checkThis": "Schau dir das an",
            "updated": "Aktualisiert",
            "conversationsCount": "%d Unterhaltungen",
            "searchChats": "Chats suchen",
            "filter": "Filter",
            "allChats": "Alle Chats",
            "groups": "Gruppen",
            "bots": "Bots",
            "botChatsWillAppear": "Bot-Chats werden hier angezeigt.",
            "noChatsFound": "Keine Chats gefunden.",
            "createGroup": "Gruppe erstellen",
            "groupName": "Gruppenname",
            "groupNamePlaceholder": "Wochenendpläne, Launch-Team...",
            "chooseMembers": "Mitglieder auswählen",
            "selectedMembersCount": "%d ausgewählt",
            "invitePeople": "Leute einladen",
            "allContactsInGroup": "Alle Kontakte sind bereits in dieser Gruppe.",
            "contactsSubtitle": "Per Telefon, E-Mail oder Spitzname einladen.",
            "contactLookupPlaceholder": "Telefon, E-Mail oder @Spitzname",
            "incomingRequests": "Eingehende Anfragen",
            "yourContacts": "Deine Kontakte",
            "noContactsYet": "Noch keine Kontakte.",
            "message": "Nachricht",
            "sentInvitations": "Gesendete Einladungen",
            "pending": "Ausstehend",
            "accept": "Annehmen",
            "decline": "Ablehnen",
            "profileSubtitle": "Verwalte deine öffentliche Identität.",
            "firstName": "Vorname",
            "lastName": "Nachname",
            "saveProfile": "Profil speichern",
            "memberSince": "Mitglied seit",
            "authSignupSubtitle": "Erstelle dein Konto mit E-Mail oder Google.",
            "authLoginSubtitle": "Melde dich mit E-Mail oder Google an.",
            "continueWithGoogle": "Mit Google fortfahren",
            "or": "oder",
            "authenticationMode": "Anmeldemodus",
            "login": "Anmelden",
            "register": "Registrieren",
            "createAccount": "Konto erstellen",
            "password": "Passwort",
            "confirmPassword": "Passwort bestätigen",
            "back": "Zurück",
            "search": "Suchen",
            "cancel": "Abbrechen",
            "chatInfo": "Chat-Info",
            "contactInfo": "Kontakt-Info",
            "links": "Links",
            "translateChat": "Übersetzen",
            "stopTranslation": "Übersetzung stoppen",
            "translationEnabledForChat": "Übersetzung nach %@ ist aktiviert.",
            "translationDisabledForChat": "Übersetzung ist deaktiviert.",
            "clearHistory": "Verlauf löschen",
            "deleteChat": "Chat löschen",
            "attachmentsReady": "Anhänge sind bereit für die Backend-Anbindung.",
            "addAttachment": "Anhang hinzufügen",
            "photosAndVideos": "Fotos & Videos",
            "photosAndVideosDetail": "Wähle Medien aus deiner Bibliothek.",
            "files": "Dateien",
            "filesDetail": "Dokumente und Dateien anhängen.",
            "photoAttachment": "Foto",
            "videoAttachment": "Video",
            "fileAttachment": "Datei",
            "attachmentPrefix": "Anhang",
            "attachmentsAdded": "%d Anhang/Anhänge hinzugefügt.",
            "fileImportFailed": "Diese Datei konnte nicht hinzugefügt werden.",
            "removeAttachment": "Anhang entfernen",
            "participants": "%d Teilnehmer",
            "members": "Mitglieder",
            "linksAndDocs": "Links und Dokumente",
            "noSharedLinksYet": "Noch keine geteilten Links.",
            "loginSuccessful": "Anmeldung erfolgreich.",
            "googleSignInFailed": "Google-Anmeldung fehlgeschlagen.",
            "enterValidEmail": "Gib eine gültige E-Mail-Adresse ein.",
            "passwordMin": "Das Passwort muss mindestens 8 Zeichen haben.",
            "displayNameMin": "Der Anzeigename muss mindestens 2 Zeichen haben.",
            "usernameInvalid": "Der Benutzername darf nur Buchstaben, Zahlen und Unterstriche enthalten.",
            "enterValidPhone": "Gib eine gültige Telefonnummer ein.",
            "passwordsNoMatch": "Die Passwörter stimmen nicht überein.",
            "accountCreatedEmailVerification": "Konto erstellt. Die E-Mail-Verifizierung ist bereit für die Backend-Anbindung.",
            "messageCannotBeEmpty": "Die Nachricht darf nicht leer sein.",
            "messageTooLong": "Die Nachricht ist zu lang. Halte sie unter 2000 Zeichen.",
            "enterContactLookup": "Gib Telefon, E-Mail oder @Spitzname ein.",
            "noUserFound": "Kein Benutzer mit diesem Telefon, dieser E-Mail oder diesem Spitznamen gefunden.",
            "invitationSent": "Einladung an %@ gesendet.",
            "invitationAccepted": "Einladung angenommen. Du kannst diesem Kontakt jetzt schreiben.",
            "invitationDeclined": "Einladung abgelehnt.",
            "chatHistoryDeleted": "Chatverlauf gelöscht.",
            "chatDeleted": "Chat gelöscht.",
            "profileUpdated": "Profil aktualisiert.",
            "enterGroupName": "Gib einen Gruppennamen ein.",
            "selectAtLeastOneGroupMember": "Wähle mindestens einen Kontakt für die Gruppe aus.",
            "groupCreated": "Gruppe erstellt.",
            "addedToGroup": "%@ wurde der Gruppe hinzugefügt.",
            "addedPeopleToGroup": "%d Personen wurden der Gruppe hinzugefügt."
        ],
        "th": [
            "chats": "แชท",
            "contacts": "รายชื่อ",
            "settings": "การตั้งค่า",
            "profile": "โปรไฟล์",
            "notifications": "การแจ้งเตือน",
            "languages": "ภาษา",
            "devices": "อุปกรณ์",
            "settingsSubtitle": "โปรไฟล์ การแจ้งเตือน ภาษา และอุปกรณ์",
            "username": "ชื่อผู้ใช้",
            "displayName": "ชื่อที่แสดง",
            "email": "อีเมล",
            "phone": "โทรศัพท์",
            "notSet": "ยังไม่ได้ตั้งค่า",
            "appLanguageTitle": "ภาษาของแอป",
            "appLanguageDetail": "ใช้กับหน้าจอ เมนู และปุ่มของ KnotLink",
            "autoTranslationTitle": "เปิดการแปลอัตโนมัติ",
            "translateToTitle": "แปลข้อความเป็น",
            "translateToDetail": "ข้อความขาเข้าจะใช้ภาษานี้",
            "saveLanguageSettings": "บันทึกการตั้งค่าภาษา",
            "languageSavedOn": "ตั้งค่าภาษาแอปเป็น %@ แล้ว เปิดการแปลอัตโนมัติเป็น %@",
            "languageSavedOff": "ตั้งค่าภาษาแอปเป็น %@ แล้ว ปิดการแปลอัตโนมัติ",
            "passwordChangesUnavailable": "ไม่สามารถเปลี่ยนรหัสผ่านได้",
            "oauthPasswordUnavailable": "พื้นที่ทำงานนี้ใช้การลงชื่อเข้าใช้ด้วย OAuth เท่านั้น จึงไม่สามารถเปลี่ยนรหัสผ่านจากการตั้งค่าได้",
            "logOut": "ออกจากระบบ",
            "enablePushNotifications": "เปิดการแจ้งเตือนแบบพุช",
            "showMessagePreviews": "แสดงตัวอย่างข้อความ",
            "notifyContactRequests": "แจ้งเตือนคำขอเพิ่มรายชื่อ",
            "notificationSound": "เสียงแจ้งเตือน",
            "soundDefault": "ค่าเริ่มต้น",
            "soundSoftChime": "เสียงกระดิ่งเบา",
            "soundClassicPing": "เสียงปิงคลาสสิก",
            "soundSilent": "เงียบ",
            "saveNotificationSettings": "บันทึกการตั้งค่าการแจ้งเตือน",
            "notificationSettingsSaved": "บันทึกการตั้งค่าการแจ้งเตือนแล้ว",
            "thisDevice": "อุปกรณ์นี้",
            "activeNow": "ใช้งานอยู่ตอนนี้",
            "lastActiveJustNow": "ใช้งานล่าสุด: ตอนนี้",
            "current": "ปัจจุบัน",
            "saveDevicePreferences": "บันทึกการตั้งค่าอุปกรณ์",
            "devicePreferencesSaved": "บันทึกการตั้งค่าอุปกรณ์แล้ว",
            "selectChat": "เลือกแชท",
            "conversationOpensHere": "บทสนทนาของคุณจะเปิดที่นี่",
            "checkThis": "ดูสิ่งนี้",
            "updated": "อัปเดตแล้ว",
            "conversationsCount": "%d บทสนทนา",
            "searchChats": "ค้นหาแชท",
            "filter": "ตัวกรอง",
            "allChats": "แชททั้งหมด",
            "groups": "กลุ่ม",
            "bots": "บอท",
            "botChatsWillAppear": "แชทบอทจะแสดงที่นี่",
            "noChatsFound": "ไม่พบแชท",
            "createGroup": "สร้างกลุ่ม",
            "groupName": "ชื่อกลุ่ม",
            "groupNamePlaceholder": "แผนสุดสัปดาห์, ทีมเปิดตัว...",
            "chooseMembers": "เลือกสมาชิก",
            "selectedMembersCount": "เลือกแล้ว %d",
            "invitePeople": "เชิญผู้คน",
            "allContactsInGroup": "รายชื่อทั้งหมดอยู่ในกลุ่มนี้แล้ว",
            "contactsSubtitle": "เชิญด้วยโทรศัพท์ อีเมล หรือชื่อเล่น",
            "contactLookupPlaceholder": "โทรศัพท์ อีเมล หรือ @ชื่อเล่น",
            "incomingRequests": "คำขอที่เข้ามา",
            "yourContacts": "รายชื่อของคุณ",
            "noContactsYet": "ยังไม่มีรายชื่อ",
            "message": "ข้อความ",
            "sentInvitations": "คำเชิญที่ส่งแล้ว",
            "pending": "รอดำเนินการ",
            "accept": "ยอมรับ",
            "decline": "ปฏิเสธ",
            "profileSubtitle": "จัดการตัวตนสาธารณะของคุณ",
            "firstName": "ชื่อ",
            "lastName": "นามสกุล",
            "saveProfile": "บันทึกโปรไฟล์",
            "memberSince": "เป็นสมาชิกตั้งแต่",
            "authSignupSubtitle": "สร้างบัญชีด้วยอีเมลหรือ Google",
            "authLoginSubtitle": "เข้าสู่ระบบด้วยอีเมลหรือ Google",
            "continueWithGoogle": "ดำเนินการต่อด้วย Google",
            "or": "หรือ",
            "authenticationMode": "โหมดการยืนยันตัวตน",
            "login": "เข้าสู่ระบบ",
            "register": "สมัครสมาชิก",
            "createAccount": "สร้างบัญชี",
            "password": "รหัสผ่าน",
            "confirmPassword": "ยืนยันรหัสผ่าน",
            "back": "กลับ",
            "search": "ค้นหา",
            "cancel": "ยกเลิก",
            "chatInfo": "ข้อมูลแชท",
            "contactInfo": "ข้อมูลผู้ติดต่อ",
            "links": "ลิงก์",
            "translateChat": "แปล",
            "stopTranslation": "หยุดแปล",
            "translationEnabledForChat": "เปิดการแปลเป็น %@ แล้ว",
            "translationDisabledForChat": "ปิดการแปลแล้ว",
            "clearHistory": "ล้างประวัติ",
            "deleteChat": "ลบแชท",
            "attachmentsReady": "ไฟล์แนบพร้อมเชื่อมต่อกับแบ็กเอนด์แล้ว",
            "addAttachment": "เพิ่มไฟล์แนบ",
            "photosAndVideos": "รูปภาพและวิดีโอ",
            "photosAndVideosDetail": "เลือกสื่อจากคลังของคุณ",
            "files": "ไฟล์",
            "filesDetail": "แนบเอกสารและไฟล์",
            "photoAttachment": "รูปภาพ",
            "videoAttachment": "วิดีโอ",
            "fileAttachment": "ไฟล์",
            "attachmentPrefix": "ไฟล์แนบ",
            "attachmentsAdded": "เพิ่มไฟล์แนบ %d รายการแล้ว",
            "fileImportFailed": "ไม่สามารถเพิ่มไฟล์นั้นได้",
            "removeAttachment": "ลบไฟล์แนบ",
            "participants": "ผู้เข้าร่วม %d คน",
            "members": "สมาชิก",
            "linksAndDocs": "ลิงก์และเอกสาร",
            "noSharedLinksYet": "ยังไม่มีลิงก์ที่แชร์",
            "loginSuccessful": "เข้าสู่ระบบสำเร็จ",
            "googleSignInFailed": "เข้าสู่ระบบด้วย Google ไม่สำเร็จ",
            "enterValidEmail": "ป้อนที่อยู่อีเมลที่ถูกต้อง",
            "passwordMin": "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
            "displayNameMin": "ชื่อที่แสดงต้องมีอย่างน้อย 2 ตัวอักษร",
            "usernameInvalid": "ชื่อผู้ใช้ใช้ได้เฉพาะตัวอักษร ตัวเลข และขีดล่าง",
            "enterValidPhone": "ป้อนหมายเลขโทรศัพท์ที่ถูกต้อง",
            "passwordsNoMatch": "รหัสผ่านไม่ตรงกัน",
            "accountCreatedEmailVerification": "สร้างบัญชีแล้ว การยืนยันอีเมลพร้อมเชื่อมต่อกับแบ็กเอนด์",
            "messageCannotBeEmpty": "ข้อความต้องไม่ว่างเปล่า",
            "messageTooLong": "ข้อความยาวเกินไป กรุณาไม่เกิน 2000 ตัวอักษร",
            "enterContactLookup": "ป้อนโทรศัพท์ อีเมล หรือ @ชื่อเล่น",
            "noUserFound": "ไม่พบผู้ใช้ด้วยโทรศัพท์ อีเมล หรือชื่อเล่นนั้น",
            "invitationSent": "ส่งคำเชิญถึง %@ แล้ว",
            "invitationAccepted": "ยอมรับคำเชิญแล้ว ตอนนี้คุณสามารถแชทกับผู้ติดต่อนี้ได้",
            "invitationDeclined": "ปฏิเสธคำเชิญแล้ว",
            "chatHistoryDeleted": "ลบประวัติแชทแล้ว",
            "chatDeleted": "ลบแชทแล้ว",
            "profileUpdated": "อัปเดตโปรไฟล์แล้ว",
            "enterGroupName": "ใส่ชื่อกลุ่ม",
            "selectAtLeastOneGroupMember": "เลือกอย่างน้อยหนึ่งรายชื่อสำหรับกลุ่ม",
            "groupCreated": "สร้างกลุ่มแล้ว",
            "addedToGroup": "เพิ่ม %@ ในกลุ่มแล้ว",
            "addedPeopleToGroup": "เพิ่ม %d คนในกลุ่มแล้ว"
        ],
        "uk": [
            "chats": "Чати",
            "contacts": "Контакти",
            "settings": "Налаштування",
            "profile": "Профіль",
            "notifications": "Сповіщення",
            "languages": "Мови",
            "devices": "Пристрої",
            "settingsSubtitle": "Профіль, сповіщення, мова та пристрої.",
            "username": "Ім’я користувача",
            "displayName": "Відображуване ім’я",
            "email": "Ел. пошта",
            "phone": "Телефон",
            "notSet": "Не вказано",
            "appLanguageTitle": "Мова застосунку",
            "appLanguageDetail": "Використовується для екранів, меню й кнопок KnotLink.",
            "autoTranslationTitle": "Увімкнути автопереклад",
            "translateToTitle": "Перекладати повідомлення на",
            "translateToDetail": "Вхідні повідомлення використовуватимуть цю мову.",
            "saveLanguageSettings": "Зберегти мовні налаштування",
            "languageSavedOn": "Мову застосунку встановлено на %@. Автопереклад на %@ увімкнено.",
            "languageSavedOff": "Мову застосунку встановлено на %@. Автопереклад вимкнено.",
            "passwordChangesUnavailable": "Зміна пароля недоступна",
            "oauthPasswordUnavailable": "Цей робочий простір використовує лише вхід через OAuth. Змінити пароль у налаштуваннях неможливо.",
            "logOut": "Вийти",
            "enablePushNotifications": "Увімкнути push-сповіщення",
            "showMessagePreviews": "Показувати попередній перегляд повідомлень",
            "notifyContactRequests": "Сповіщати про запити контактів",
            "notificationSound": "Звук сповіщень",
            "soundDefault": "За замовчуванням",
            "soundSoftChime": "М’який дзвінок",
            "soundClassicPing": "Класичний сигнал",
            "soundSilent": "Без звуку",
            "saveNotificationSettings": "Зберегти налаштування сповіщень",
            "notificationSettingsSaved": "Налаштування сповіщень збережено.",
            "thisDevice": "Цей пристрій",
            "activeNow": "Активний зараз",
            "lastActiveJustNow": "Остання активність: щойно",
            "current": "Поточний",
            "saveDevicePreferences": "Зберегти налаштування пристрою",
            "devicePreferencesSaved": "Налаштування пристрою збережено.",
            "selectChat": "Виберіть чат",
            "conversationOpensHere": "Тут відкриється ваша розмова.",
            "checkThis": "Перевірте це",
            "updated": "Оновлено",
            "conversationsCount": "%d розмов",
            "searchChats": "Пошук чатів",
            "filter": "Фільтр",
            "allChats": "Усі чати",
            "groups": "Групи",
            "bots": "Боти",
            "botChatsWillAppear": "Чати з ботами з’являться тут.",
            "noChatsFound": "Чати не знайдено.",
            "createGroup": "Створити групу",
            "groupName": "Назва групи",
            "groupNamePlaceholder": "Плани на вихідні, Команда запуску...",
            "chooseMembers": "Виберіть учасників",
            "selectedMembersCount": "%d вибрано",
            "invitePeople": "Запросити людей",
            "allContactsInGroup": "Усі контакти вже в цій групі.",
            "contactsSubtitle": "Запрошуйте за телефоном, поштою або ніком.",
            "contactLookupPlaceholder": "Телефон, пошта або @нік",
            "incomingRequests": "Вхідні запити",
            "yourContacts": "Ваші контакти",
            "noContactsYet": "Контактів поки немає.",
            "message": "Повідомлення",
            "sentInvitations": "Надіслані запрошення",
            "pending": "Очікує",
            "accept": "Прийняти",
            "decline": "Відхилити",
            "profileSubtitle": "Керуйте своєю публічною ідентичністю.",
            "firstName": "Ім’я",
            "lastName": "Прізвище",
            "saveProfile": "Зберегти профіль",
            "memberSince": "Учасник з",
            "authSignupSubtitle": "Створіть акаунт через пошту або Google.",
            "authLoginSubtitle": "Увійдіть через пошту або Google.",
            "continueWithGoogle": "Продовжити з Google",
            "or": "або",
            "authenticationMode": "Режим входу",
            "login": "Увійти",
            "register": "Зареєструватися",
            "createAccount": "Створити акаунт",
            "password": "Пароль",
            "confirmPassword": "Підтвердьте пароль",
            "back": "Назад",
            "search": "Пошук",
            "cancel": "Скасувати",
            "chatInfo": "Інформація про чат",
            "contactInfo": "Інформація про контакт",
            "links": "Посилання",
            "translateChat": "Перекласти",
            "stopTranslation": "Зупинити переклад",
            "translationEnabledForChat": "Переклад на %@ увімкнено.",
            "translationDisabledForChat": "Переклад вимкнено.",
            "clearHistory": "Очистити історію",
            "deleteChat": "Видалити чат",
            "attachmentsReady": "Вкладення готові до підключення бекенду.",
            "addAttachment": "Додати вкладення",
            "photosAndVideos": "Фото й відео",
            "photosAndVideosDetail": "Виберіть медіа з бібліотеки.",
            "files": "Файли",
            "filesDetail": "Прикріпіть документи й файли.",
            "photoAttachment": "Фото",
            "videoAttachment": "Відео",
            "fileAttachment": "Файл",
            "attachmentPrefix": "Вкладення",
            "attachmentsAdded": "Додано вкладень: %d.",
            "fileImportFailed": "Не вдалося додати цей файл.",
            "removeAttachment": "Видалити вкладення",
            "participants": "%d учасників",
            "members": "Учасники",
            "linksAndDocs": "Посилання й документи",
            "noSharedLinksYet": "Спільних посилань поки немає.",
            "loginSuccessful": "Вхід виконано.",
            "googleSignInFailed": "Вхід через Google не вдався.",
            "enterValidEmail": "Введіть коректну адресу ел. пошти.",
            "passwordMin": "Пароль має містити щонайменше 8 символів.",
            "displayNameMin": "Відображуване ім’я має містити щонайменше 2 символи.",
            "usernameInvalid": "Ім’я користувача може містити лише літери, цифри й підкреслення.",
            "enterValidPhone": "Введіть коректний номер телефону.",
            "passwordsNoMatch": "Паролі не збігаються.",
            "accountCreatedEmailVerification": "Акаунт створено. Перевірка пошти готова до підключення бекенду.",
            "messageCannotBeEmpty": "Повідомлення не може бути порожнім.",
            "messageTooLong": "Повідомлення занадто довге. Не більше 2000 символів.",
            "enterContactLookup": "Введіть телефон, пошту або @нік.",
            "noUserFound": "Користувача з таким телефоном, поштою або ніком не знайдено.",
            "invitationSent": "Запрошення надіслано: %@.",
            "invitationAccepted": "Запрошення прийнято. Тепер можна писати цьому контакту.",
            "invitationDeclined": "Запрошення відхилено.",
            "chatHistoryDeleted": "Історію чату видалено.",
            "chatDeleted": "Чат видалено.",
            "profileUpdated": "Профіль оновлено.",
            "enterGroupName": "Введіть назву групи.",
            "selectAtLeastOneGroupMember": "Виберіть хоча б один контакт для групи.",
            "groupCreated": "Групу створено.",
            "addedToGroup": "%@ додано до групи.",
            "addedPeopleToGroup": "%d людей додано до групи."
        ],
        "pl": [
            "chats": "Czaty",
            "contacts": "Kontakty",
            "settings": "Ustawienia",
            "profile": "Profil",
            "notifications": "Powiadomienia",
            "languages": "Języki",
            "devices": "Urządzenia",
            "settingsSubtitle": "Profil, powiadomienia, język i urządzenia.",
            "username": "Nazwa użytkownika",
            "displayName": "Nazwa wyświetlana",
            "email": "E-mail",
            "phone": "Telefon",
            "notSet": "Nie ustawiono",
            "appLanguageTitle": "Język aplikacji",
            "appLanguageDetail": "Używany na ekranach, w menu i przyciskach KnotLink.",
            "autoTranslationTitle": "Włącz automatyczne tłumaczenie",
            "translateToTitle": "Tłumacz wiadomości na",
            "translateToDetail": "Wiadomości przychodzące będą używać tego języka.",
            "saveLanguageSettings": "Zapisz ustawienia języka",
            "languageSavedOn": "Język aplikacji ustawiono na %@. Automatyczne tłumaczenie na %@ jest włączone.",
            "languageSavedOff": "Język aplikacji ustawiono na %@. Automatyczne tłumaczenie jest wyłączone.",
            "passwordChangesUnavailable": "Zmiana hasła niedostępna",
            "oauthPasswordUnavailable": "Ten obszar roboczy używa tylko logowania OAuth. Zmiana hasła nie jest dostępna w ustawieniach.",
            "logOut": "Wyloguj",
            "enablePushNotifications": "Włącz powiadomienia push",
            "showMessagePreviews": "Pokazuj podgląd wiadomości",
            "notifyContactRequests": "Powiadamiaj o prośbach o kontakt",
            "notificationSound": "Dźwięk powiadomienia",
            "soundDefault": "Domyślny",
            "soundSoftChime": "Delikatny dzwonek",
            "soundClassicPing": "Klasyczny ping",
            "soundSilent": "Cisza",
            "saveNotificationSettings": "Zapisz ustawienia powiadomień",
            "notificationSettingsSaved": "Ustawienia powiadomień zapisane.",
            "thisDevice": "To urządzenie",
            "activeNow": "Aktywne teraz",
            "lastActiveJustNow": "Ostatnia aktywność: teraz",
            "current": "Bieżące",
            "saveDevicePreferences": "Zapisz preferencje urządzenia",
            "devicePreferencesSaved": "Preferencje urządzenia zapisane.",
            "selectChat": "Wybierz czat",
            "conversationOpensHere": "Twoja rozmowa otworzy się tutaj.",
            "checkThis": "Sprawdź to",
            "updated": "Zaktualizowano",
            "conversationsCount": "%d rozmów",
            "searchChats": "Szukaj czatów",
            "filter": "Filtr",
            "allChats": "Wszystkie czaty",
            "groups": "Grupy",
            "bots": "Boty",
            "botChatsWillAppear": "Czaty z botami pojawią się tutaj.",
            "noChatsFound": "Nie znaleziono czatów.",
            "createGroup": "Utwórz grupę",
            "groupName": "Nazwa grupy",
            "groupNamePlaceholder": "Plany na weekend, Zespół startowy...",
            "chooseMembers": "Wybierz członków",
            "selectedMembersCount": "Wybrano %d",
            "invitePeople": "Zaproś osoby",
            "allContactsInGroup": "Wszystkie kontakty są już w tej grupie.",
            "contactsSubtitle": "Zaproś przez telefon, e-mail lub pseudonim.",
            "contactLookupPlaceholder": "Telefon, e-mail lub @pseudonim",
            "incomingRequests": "Przychodzące prośby",
            "yourContacts": "Twoje kontakty",
            "noContactsYet": "Brak kontaktów.",
            "message": "Wiadomość",
            "sentInvitations": "Wysłane zaproszenia",
            "pending": "Oczekuje",
            "accept": "Akceptuj",
            "decline": "Odrzuć",
            "profileSubtitle": "Zarządzaj swoją publiczną tożsamością.",
            "firstName": "Imię",
            "lastName": "Nazwisko",
            "saveProfile": "Zapisz profil",
            "memberSince": "Członek od",
            "authSignupSubtitle": "Utwórz konto przez e-mail lub Google.",
            "authLoginSubtitle": "Zaloguj się przez e-mail lub Google.",
            "continueWithGoogle": "Kontynuuj z Google",
            "or": "lub",
            "authenticationMode": "Tryb logowania",
            "login": "Zaloguj",
            "register": "Zarejestruj",
            "createAccount": "Utwórz konto",
            "password": "Hasło",
            "confirmPassword": "Potwierdź hasło",
            "back": "Wstecz",
            "search": "Szukaj",
            "cancel": "Anuluj",
            "chatInfo": "Informacje o czacie",
            "contactInfo": "Informacje o kontakcie",
            "links": "Linki",
            "translateChat": "Tłumacz",
            "stopTranslation": "Zatrzymaj tłumaczenie",
            "translationEnabledForChat": "Tłumaczenie na %@ jest włączone.",
            "translationDisabledForChat": "Tłumaczenie jest wyłączone.",
            "clearHistory": "Wyczyść historię",
            "deleteChat": "Usuń czat",
            "attachmentsReady": "Załączniki są gotowe do podłączenia backendu.",
            "addAttachment": "Dodaj załącznik",
            "photosAndVideos": "Zdjęcia i filmy",
            "photosAndVideosDetail": "Wybierz multimedia z biblioteki.",
            "files": "Pliki",
            "filesDetail": "Dołącz dokumenty i pliki.",
            "photoAttachment": "Zdjęcie",
            "videoAttachment": "Film",
            "fileAttachment": "Plik",
            "attachmentPrefix": "Załącznik",
            "attachmentsAdded": "Dodano załączniki: %d.",
            "fileImportFailed": "Nie można dodać tego pliku.",
            "removeAttachment": "Usuń załącznik",
            "participants": "%d uczestników",
            "members": "Członkowie",
            "linksAndDocs": "Linki i dokumenty",
            "noSharedLinksYet": "Brak udostępnionych linków.",
            "loginSuccessful": "Logowanie udane.",
            "googleSignInFailed": "Logowanie przez Google nie powiodło się.",
            "enterValidEmail": "Podaj prawidłowy adres e-mail.",
            "passwordMin": "Hasło musi mieć co najmniej 8 znaków.",
            "displayNameMin": "Nazwa wyświetlana musi mieć co najmniej 2 znaki.",
            "usernameInvalid": "Nazwa użytkownika może zawierać tylko litery, cyfry i podkreślenia.",
            "enterValidPhone": "Podaj prawidłowy numer telefonu.",
            "passwordsNoMatch": "Hasła nie są takie same.",
            "accountCreatedEmailVerification": "Konto utworzone. Weryfikacja e-mail jest gotowa do podłączenia backendu.",
            "messageCannotBeEmpty": "Wiadomość nie może być pusta.",
            "messageTooLong": "Wiadomość jest za długa. Maksymalnie 2000 znaków.",
            "enterContactLookup": "Podaj telefon, e-mail lub @pseudonim.",
            "noUserFound": "Nie znaleziono użytkownika z takim telefonem, e-mailem lub pseudonimem.",
            "invitationSent": "Zaproszenie wysłane do %@.",
            "invitationAccepted": "Zaproszenie zaakceptowane. Możesz teraz pisać do tego kontaktu.",
            "invitationDeclined": "Zaproszenie odrzucone.",
            "chatHistoryDeleted": "Historia czatu usunięta.",
            "chatDeleted": "Czat usunięty.",
            "profileUpdated": "Profil zaktualizowany.",
            "enterGroupName": "Wpisz nazwę grupy.",
            "selectAtLeastOneGroupMember": "Wybierz co najmniej jeden kontakt do grupy.",
            "groupCreated": "Grupa utworzona.",
            "addedToGroup": "Dodano %@ do grupy.",
            "addedPeopleToGroup": "Dodano %d osób do grupy."
        ],
        "zh": [
            "chats": "聊天",
            "contacts": "联系人",
            "settings": "设置",
            "profile": "个人资料",
            "notifications": "通知",
            "languages": "语言",
            "devices": "设备",
            "settingsSubtitle": "个人资料、通知、语言和设备。",
            "username": "用户名",
            "displayName": "显示名称",
            "email": "电子邮件",
            "phone": "电话",
            "notSet": "未设置",
            "appLanguageTitle": "应用语言",
            "appLanguageDetail": "用于 KnotLink 的屏幕、菜单和按钮。",
            "autoTranslationTitle": "启用自动翻译",
            "translateToTitle": "将消息翻译为",
            "translateToDetail": "收到的消息将使用这个目标语言。",
            "saveLanguageSettings": "保存语言设置",
            "languageSavedOn": "应用语言已设置为 %@。自动翻译为 %@ 已开启。",
            "languageSavedOff": "应用语言已设置为 %@。自动翻译已关闭。",
            "passwordChangesUnavailable": "无法更改密码",
            "oauthPasswordUnavailable": "此工作区仅使用 OAuth 登录。无法在设置中更改密码。",
            "logOut": "退出登录",
            "enablePushNotifications": "启用推送通知",
            "showMessagePreviews": "显示消息预览",
            "notifyContactRequests": "联系人请求通知",
            "notificationSound": "通知声音",
            "soundDefault": "默认",
            "soundSoftChime": "轻柔铃声",
            "soundClassicPing": "经典提示音",
            "soundSilent": "静音",
            "saveNotificationSettings": "保存通知设置",
            "notificationSettingsSaved": "通知设置已保存。",
            "thisDevice": "此设备",
            "activeNow": "当前在线",
            "lastActiveJustNow": "上次活动：刚刚",
            "current": "当前",
            "saveDevicePreferences": "保存设备偏好",
            "devicePreferencesSaved": "设备偏好已保存。",
            "selectChat": "选择聊天",
            "conversationOpensHere": "你的对话会在这里打开。",
            "checkThis": "查看这个",
            "updated": "已更新",
            "conversationsCount": "%d 个对话",
            "searchChats": "搜索聊天",
            "filter": "筛选",
            "allChats": "全部聊天",
            "groups": "群组",
            "bots": "机器人",
            "botChatsWillAppear": "机器人聊天会显示在这里。",
            "noChatsFound": "未找到聊天。",
            "createGroup": "创建群组",
            "groupName": "群组名称",
            "groupNamePlaceholder": "周末计划、发布团队...",
            "chooseMembers": "选择成员",
            "selectedMembersCount": "已选择 %d 个",
            "invitePeople": "邀请成员",
            "allContactsInGroup": "所有联系人都已在此群组中。",
            "contactsSubtitle": "通过电话、电子邮件或昵称邀请。",
            "contactLookupPlaceholder": "电话、电子邮件或 @昵称",
            "incomingRequests": "收到的请求",
            "yourContacts": "你的联系人",
            "noContactsYet": "暂无联系人。",
            "message": "消息",
            "sentInvitations": "已发送邀请",
            "pending": "待处理",
            "accept": "接受",
            "decline": "拒绝",
            "profileSubtitle": "管理你的公开身份。",
            "firstName": "名字",
            "lastName": "姓氏",
            "saveProfile": "保存资料",
            "memberSince": "加入时间",
            "authSignupSubtitle": "使用电子邮件或 Google 创建账户。",
            "authLoginSubtitle": "使用电子邮件或 Google 登录。",
            "continueWithGoogle": "继续使用 Google",
            "or": "或",
            "authenticationMode": "身份验证模式",
            "login": "登录",
            "register": "注册",
            "createAccount": "创建账户",
            "password": "密码",
            "confirmPassword": "确认密码",
            "back": "返回",
            "search": "搜索",
            "cancel": "取消",
            "chatInfo": "聊天信息",
            "contactInfo": "联系人信息",
            "links": "链接",
            "translateChat": "翻译",
            "stopTranslation": "停止翻译",
            "translationEnabledForChat": "已开启翻译为 %@。",
            "translationDisabledForChat": "翻译已关闭。",
            "clearHistory": "清除历史",
            "deleteChat": "删除聊天",
            "attachmentsReady": "附件已准备好连接后端。",
            "addAttachment": "添加附件",
            "photosAndVideos": "照片和视频",
            "photosAndVideosDetail": "从你的图库选择媒体。",
            "files": "文件",
            "filesDetail": "附加文档和文件。",
            "photoAttachment": "照片",
            "videoAttachment": "视频",
            "fileAttachment": "文件",
            "attachmentPrefix": "附件",
            "attachmentsAdded": "已添加 %d 个附件。",
            "fileImportFailed": "无法添加该文件。",
            "removeAttachment": "移除附件",
            "participants": "%d 位参与者",
            "members": "成员",
            "linksAndDocs": "链接和文档",
            "noSharedLinksYet": "暂无共享链接。",
            "loginSuccessful": "登录成功。",
            "googleSignInFailed": "Google 登录失败。",
            "enterValidEmail": "请输入有效的电子邮件地址。",
            "passwordMin": "密码至少需要 8 个字符。",
            "displayNameMin": "显示名称至少需要 2 个字符。",
            "usernameInvalid": "用户名只能使用字母、数字和下划线。",
            "enterValidPhone": "请输入有效的电话号码。",
            "passwordsNoMatch": "密码不匹配。",
            "accountCreatedEmailVerification": "账户已创建。电子邮件验证已准备好连接后端。",
            "messageCannotBeEmpty": "消息不能为空。",
            "messageTooLong": "消息太长。请控制在 2000 个字符以内。",
            "enterContactLookup": "请输入电话、电子邮件或 @昵称。",
            "noUserFound": "未找到使用该电话、电子邮件或昵称的用户。",
            "invitationSent": "已向 %@ 发送邀请。",
            "invitationAccepted": "邀请已接受。你现在可以与此联系人聊天。",
            "invitationDeclined": "邀请已拒绝。",
            "chatHistoryDeleted": "聊天记录已删除。",
            "chatDeleted": "聊天已删除。",
            "profileUpdated": "资料已更新。",
            "enterGroupName": "请输入群组名称。",
            "selectAtLeastOneGroupMember": "请至少选择一个联系人加入群组。",
            "groupCreated": "群组已创建。",
            "addedToGroup": "%@ 已加入群组。",
            "addedPeopleToGroup": "%d 人已加入群组。"
        ],
        "hi": [
            "chats": "चैट",
            "contacts": "संपर्क",
            "settings": "सेटिंग्स",
            "profile": "प्रोफ़ाइल",
            "notifications": "सूचनाएँ",
            "languages": "भाषाएँ",
            "devices": "डिवाइस",
            "settingsSubtitle": "प्रोफ़ाइल, सूचनाएँ, भाषा और डिवाइस।",
            "username": "उपयोगकर्ता नाम",
            "displayName": "दिखाया जाने वाला नाम",
            "email": "ईमेल",
            "phone": "फ़ोन",
            "notSet": "सेट नहीं",
            "appLanguageTitle": "ऐप भाषा",
            "appLanguageDetail": "KnotLink की स्क्रीन, मेनू और बटन के लिए उपयोग की जाती है।",
            "autoTranslationTitle": "ऑटो-अनुवाद चालू करें",
            "translateToTitle": "संदेशों का अनुवाद करें",
            "translateToDetail": "आने वाले संदेश इस लक्ष्य भाषा का उपयोग करेंगे।",
            "saveLanguageSettings": "भाषा सेटिंग्स सहेजें",
            "languageSavedOn": "ऐप भाषा %@ पर सेट की गई। %@ में ऑटो-अनुवाद चालू है।",
            "languageSavedOff": "ऐप भाषा %@ पर सेट की गई। ऑटो-अनुवाद बंद है।",
            "passwordChangesUnavailable": "पासवर्ड बदलना उपलब्ध नहीं है",
            "oauthPasswordUnavailable": "यह वर्कस्पेस केवल OAuth साइन-इन का उपयोग करता है। सेटिंग्स से पासवर्ड बदलना उपलब्ध नहीं है।",
            "logOut": "लॉग आउट",
            "enablePushNotifications": "पुश सूचनाएँ चालू करें",
            "showMessagePreviews": "संदेश पूर्वावलोकन दिखाएँ",
            "notifyContactRequests": "संपर्क अनुरोधों की सूचना दें",
            "notificationSound": "सूचना ध्वनि",
            "soundDefault": "डिफ़ॉल्ट",
            "soundSoftChime": "हल्की घंटी",
            "soundClassicPing": "क्लासिक पिंग",
            "soundSilent": "मौन",
            "saveNotificationSettings": "सूचना सेटिंग्स सहेजें",
            "notificationSettingsSaved": "सूचना सेटिंग्स सहेजी गईं।",
            "thisDevice": "यह डिवाइस",
            "activeNow": "अभी सक्रिय",
            "lastActiveJustNow": "अंतिम सक्रियता: अभी",
            "current": "वर्तमान",
            "saveDevicePreferences": "डिवाइस प्राथमिकताएँ सहेजें",
            "devicePreferencesSaved": "डिवाइस प्राथमिकताएँ सहेजी गईं।",
            "selectChat": "चैट चुनें",
            "conversationOpensHere": "आपकी बातचीत यहाँ खुलेगी।",
            "checkThis": "इसे देखें",
            "updated": "अपडेट किया गया",
            "conversationsCount": "%d बातचीत",
            "searchChats": "चैट खोजें",
            "filter": "फ़िल्टर",
            "allChats": "सभी चैट",
            "groups": "समूह",
            "bots": "बॉट",
            "botChatsWillAppear": "बॉट चैट यहाँ दिखाई देंगी।",
            "noChatsFound": "कोई चैट नहीं मिली।",
            "createGroup": "ग्रुप बनाएँ",
            "groupName": "ग्रुप का नाम",
            "groupNamePlaceholder": "वीकेंड प्लान, लॉन्च टीम...",
            "chooseMembers": "सदस्य चुनें",
            "selectedMembersCount": "%d चुने गए",
            "invitePeople": "लोगों को आमंत्रित करें",
            "allContactsInGroup": "सभी संपर्क पहले से इस ग्रुप में हैं।",
            "contactsSubtitle": "फ़ोन, ईमेल या निकनेम से आमंत्रित करें।",
            "contactLookupPlaceholder": "फ़ोन, ईमेल या @निकनेम",
            "incomingRequests": "आने वाले अनुरोध",
            "yourContacts": "आपके संपर्क",
            "noContactsYet": "अभी कोई संपर्क नहीं।",
            "message": "संदेश",
            "sentInvitations": "भेजे गए आमंत्रण",
            "pending": "लंबित",
            "accept": "स्वीकार करें",
            "decline": "अस्वीकार करें",
            "profileSubtitle": "अपनी सार्वजनिक पहचान प्रबंधित करें।",
            "firstName": "पहला नाम",
            "lastName": "अंतिम नाम",
            "saveProfile": "प्रोफ़ाइल सहेजें",
            "memberSince": "सदस्यता शुरू",
            "authSignupSubtitle": "ईमेल या Google से अपना खाता बनाएँ।",
            "authLoginSubtitle": "ईमेल या Google से साइन इन करें।",
            "continueWithGoogle": "Google के साथ जारी रखें",
            "or": "या",
            "authenticationMode": "प्रमाणीकरण मोड",
            "login": "लॉग इन",
            "register": "रजिस्टर",
            "createAccount": "खाता बनाएँ",
            "password": "पासवर्ड",
            "confirmPassword": "पासवर्ड की पुष्टि करें",
            "back": "वापस",
            "search": "खोजें",
            "cancel": "रद्द करें",
            "chatInfo": "चैट जानकारी",
            "contactInfo": "संपर्क जानकारी",
            "links": "लिंक",
            "translateChat": "अनुवाद करें",
            "stopTranslation": "अनुवाद रोकें",
            "translationEnabledForChat": "%@ में अनुवाद चालू है।",
            "translationDisabledForChat": "अनुवाद बंद है।",
            "clearHistory": "इतिहास साफ़ करें",
            "deleteChat": "चैट हटाएँ",
            "attachmentsReady": "अटैचमेंट बैकएंड से जुड़ने के लिए तैयार हैं।",
            "addAttachment": "अटैचमेंट जोड़ें",
            "photosAndVideos": "फ़ोटो और वीडियो",
            "photosAndVideosDetail": "अपनी लाइब्रेरी से मीडिया चुनें।",
            "files": "फ़ाइलें",
            "filesDetail": "दस्तावेज़ और फ़ाइलें जोड़ें।",
            "photoAttachment": "फ़ोटो",
            "videoAttachment": "वीडियो",
            "fileAttachment": "फ़ाइल",
            "attachmentPrefix": "अटैचमेंट",
            "attachmentsAdded": "%d अटैचमेंट जोड़े गए।",
            "fileImportFailed": "वह फ़ाइल नहीं जोड़ी जा सकी।",
            "removeAttachment": "अटैचमेंट हटाएँ",
            "participants": "%d प्रतिभागी",
            "members": "सदस्य",
            "linksAndDocs": "लिंक और दस्तावेज़",
            "noSharedLinksYet": "अभी कोई साझा लिंक नहीं।",
            "loginSuccessful": "लॉगिन सफल।",
            "googleSignInFailed": "Google साइन-इन विफल रहा।",
            "enterValidEmail": "मान्य ईमेल पता दर्ज करें।",
            "passwordMin": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।",
            "displayNameMin": "दिखाया जाने वाला नाम कम से कम 2 अक्षरों का होना चाहिए।",
            "usernameInvalid": "उपयोगकर्ता नाम में केवल अक्षर, अंक और अंडरस्कोर हो सकते हैं।",
            "enterValidPhone": "मान्य फ़ोन नंबर दर्ज करें।",
            "passwordsNoMatch": "पासवर्ड मेल नहीं खाते।",
            "accountCreatedEmailVerification": "खाता बनाया गया। ईमेल सत्यापन बैकएंड से जुड़ने के लिए तैयार है।",
            "messageCannotBeEmpty": "संदेश खाली नहीं हो सकता।",
            "messageTooLong": "संदेश बहुत लंबा है। इसे 2000 अक्षरों से कम रखें।",
            "enterContactLookup": "फ़ोन, ईमेल या @निकनेम दर्ज करें।",
            "noUserFound": "उस फ़ोन, ईमेल या निकनेम वाला कोई उपयोगकर्ता नहीं मिला।",
            "invitationSent": "%@ को आमंत्रण भेजा गया।",
            "invitationAccepted": "आमंत्रण स्वीकार किया गया। अब आप इस संपर्क से चैट कर सकते हैं।",
            "invitationDeclined": "आमंत्रण अस्वीकार किया गया।",
            "chatHistoryDeleted": "चैट इतिहास हटाया गया।",
            "chatDeleted": "चैट हटाई गई।",
            "profileUpdated": "प्रोफ़ाइल अपडेट की गई।",
            "enterGroupName": "ग्रुप का नाम डालें।",
            "selectAtLeastOneGroupMember": "ग्रुप के लिए कम से कम एक संपर्क चुनें।",
            "groupCreated": "ग्रुप बन गया।",
            "addedToGroup": "%@ को ग्रुप में जोड़ा गया।",
            "addedPeopleToGroup": "%d लोगों को ग्रुप में जोड़ा गया।"
        ],
        "fil": [
            "chats": "Mga Chat",
            "contacts": "Mga Contact",
            "settings": "Mga Setting",
            "profile": "Profile",
            "notifications": "Mga Notification",
            "languages": "Mga Wika",
            "devices": "Mga Device",
            "settingsSubtitle": "Profile, notification, wika, at mga device.",
            "username": "Username",
            "displayName": "Display Name",
            "email": "Email",
            "phone": "Telepono",
            "notSet": "Hindi naka-set",
            "appLanguageTitle": "Wika ng App",
            "appLanguageDetail": "Ginagamit para sa mga screen, menu, at button ng KnotLink.",
            "autoTranslationTitle": "I-enable ang auto-translation",
            "translateToTitle": "Isalin ang mga mensahe sa",
            "translateToDetail": "Gagamitin ng mga papasok na mensahe ang wikang ito.",
            "saveLanguageSettings": "I-save ang Mga Setting ng Wika",
            "languageSavedOn": "Nakatakda ang wika ng app sa %@. Naka-on ang auto-translation sa %@.",
            "languageSavedOff": "Nakatakda ang wika ng app sa %@. Naka-off ang auto-translation.",
            "passwordChangesUnavailable": "Hindi available ang pagpapalit ng password",
            "oauthPasswordUnavailable": "OAuth sign-in lang ang ginagamit ng workspace na ito. Hindi available ang pagpapalit ng password sa settings.",
            "logOut": "Mag-log out",
            "enablePushNotifications": "I-enable ang push notifications",
            "showMessagePreviews": "Ipakita ang preview ng mensahe",
            "notifyContactRequests": "Mag-notify tungkol sa contact requests",
            "notificationSound": "Tunog ng notification",
            "soundDefault": "Default",
            "soundSoftChime": "Mahinang chime",
            "soundClassicPing": "Classic ping",
            "soundSilent": "Silent",
            "saveNotificationSettings": "I-save ang Notification Settings",
            "notificationSettingsSaved": "Na-save ang notification settings.",
            "thisDevice": "Device na ito",
            "activeNow": "Aktibo ngayon",
            "lastActiveJustNow": "Huling aktibo: ngayon lang",
            "current": "Kasalukuyan",
            "saveDevicePreferences": "I-save ang Device Preferences",
            "devicePreferencesSaved": "Na-save ang device preferences.",
            "selectChat": "Pumili ng chat",
            "conversationOpensHere": "Dito magbubukas ang usapan mo.",
            "checkThis": "Tingnan ito",
            "updated": "Na-update",
            "conversationsCount": "%d usapan",
            "searchChats": "Maghanap ng Chat",
            "filter": "Filter",
            "allChats": "Lahat ng Chat",
            "groups": "Mga Group",
            "bots": "Mga Bot",
            "botChatsWillAppear": "Lalabas dito ang mga bot chat.",
            "noChatsFound": "Walang nahanap na chat.",
            "createGroup": "Gumawa ng grupo",
            "groupName": "Pangalan ng grupo",
            "groupNamePlaceholder": "Weekend plans, Launch team...",
            "chooseMembers": "Pumili ng miyembro",
            "selectedMembersCount": "%d ang napili",
            "invitePeople": "Mag-imbita ng tao",
            "allContactsInGroup": "Nasa grupong ito na ang lahat ng contact.",
            "contactsSubtitle": "Mag-imbita gamit ang telepono, email, o nickname.",
            "contactLookupPlaceholder": "Telepono, email, o @nickname",
            "incomingRequests": "Mga papasok na request",
            "yourContacts": "Mga contact mo",
            "noContactsYet": "Wala pang contact.",
            "message": "Mensahe",
            "sentInvitations": "Mga naipadalang imbitasyon",
            "pending": "Nakabinbin",
            "accept": "Tanggapin",
            "decline": "Tanggihan",
            "profileSubtitle": "Pamahalaan ang pampublikong identity mo.",
            "firstName": "Pangalan",
            "lastName": "Apelyido",
            "saveProfile": "I-save ang profile",
            "memberSince": "Miyembro mula",
            "authSignupSubtitle": "Gumawa ng account gamit ang email o Google.",
            "authLoginSubtitle": "Mag-sign in gamit ang email o Google.",
            "continueWithGoogle": "Magpatuloy gamit ang Google",
            "or": "o",
            "authenticationMode": "Authentication mode",
            "login": "Mag-log in",
            "register": "Mag-register",
            "createAccount": "Gumawa ng account",
            "password": "Password",
            "confirmPassword": "Kumpirmahin ang password",
            "back": "Bumalik",
            "search": "Maghanap",
            "cancel": "Kanselahin",
            "chatInfo": "Impormasyon ng chat",
            "contactInfo": "Impormasyon ng contact",
            "links": "Mga link",
            "translateChat": "Isalin",
            "stopTranslation": "Ihinto ang pagsasalin",
            "translationEnabledForChat": "Naka-on ang pagsasalin sa %@.",
            "translationDisabledForChat": "Naka-off ang pagsasalin.",
            "clearHistory": "I-clear ang history",
            "deleteChat": "Burahin ang chat",
            "attachmentsReady": "Handa na ang mga attachment para sa backend wiring.",
            "addAttachment": "Magdagdag ng attachment",
            "photosAndVideos": "Mga Larawan at Video",
            "photosAndVideosDetail": "Pumili ng media mula sa library mo.",
            "files": "Mga File",
            "filesDetail": "Mag-attach ng documents at files.",
            "photoAttachment": "Larawan",
            "videoAttachment": "Video",
            "fileAttachment": "File",
            "attachmentPrefix": "Attachment",
            "attachmentsAdded": "%d attachment ang naidagdag.",
            "fileImportFailed": "Hindi maidagdag ang file na iyon.",
            "removeAttachment": "Alisin ang attachment",
            "participants": "%d kalahok",
            "members": "Mga miyembro",
            "linksAndDocs": "Mga link at dokumento",
            "noSharedLinksYet": "Wala pang shared links.",
            "loginSuccessful": "Matagumpay ang login.",
            "googleSignInFailed": "Nabigo ang Google sign-in.",
            "enterValidEmail": "Maglagay ng valid na email address.",
            "passwordMin": "Dapat may hindi bababa sa 8 character ang password.",
            "displayNameMin": "Dapat may hindi bababa sa 2 character ang display name.",
            "usernameInvalid": "Letters, numbers, at underscores lang ang puwede sa username.",
            "enterValidPhone": "Maglagay ng valid na phone number.",
            "passwordsNoMatch": "Hindi tugma ang mga password.",
            "accountCreatedEmailVerification": "Nagawa na ang account. Handa na ang email verification para ikonekta sa backend.",
            "messageCannotBeEmpty": "Hindi puwedeng walang laman ang mensahe.",
            "messageTooLong": "Masyadong mahaba ang mensahe. Panatilihin itong mas mababa sa 2000 character.",
            "enterContactLookup": "Maglagay ng telepono, email, o @nickname.",
            "noUserFound": "Walang user na nahanap gamit ang telepono, email, o nickname na iyon.",
            "invitationSent": "Naipadala ang imbitasyon kay %@.",
            "invitationAccepted": "Tinanggap ang imbitasyon. Maaari ka nang makipag-chat sa contact na ito.",
            "invitationDeclined": "Tinanggihan ang imbitasyon.",
            "chatHistoryDeleted": "Nabura ang chat history.",
            "chatDeleted": "Nabura ang chat.",
            "profileUpdated": "Na-update ang profile.",
            "enterGroupName": "Maglagay ng pangalan ng grupo.",
            "selectAtLeastOneGroupMember": "Pumili ng kahit isang contact para sa grupo.",
            "groupCreated": "Nagawa na ang grupo.",
            "addedToGroup": "Naidagdag si %@ sa grupo.",
            "addedPeopleToGroup": "Naidagdag ang %d tao sa grupo."
        ],
        "fr": [
            "chats": "Discussions",
            "contacts": "Contacts",
            "settings": "Réglages",
            "profile": "Profil",
            "notifications": "Notifications",
            "languages": "Langues",
            "devices": "Appareils",
            "settingsSubtitle": "Profil, notifications, langue et appareils.",
            "username": "Nom d’utilisateur",
            "displayName": "Nom affiché",
            "email": "E-mail",
            "phone": "Téléphone",
            "notSet": "Non défini",
            "passwordChangesUnavailable": "Changement de mot de passe indisponible",
            "oauthPasswordUnavailable": "Cet espace utilise uniquement la connexion OAuth. Le changement de mot de passe n’est pas disponible dans les réglages.",
            "logOut": "Se déconnecter",
            "enablePushNotifications": "Activer les notifications push",
            "showMessagePreviews": "Afficher les aperçus de messages",
            "notifyContactRequests": "Notifier les demandes de contact",
            "notificationSound": "Son de notification",
            "soundDefault": "Par défaut",
            "soundSoftChime": "Carillon doux",
            "soundClassicPing": "Ping classique",
            "soundSilent": "Silencieux",
            "saveNotificationSettings": "Enregistrer les notifications",
            "notificationSettingsSaved": "Réglages de notification enregistrés.",
            "appLanguageTitle": "Langue de l’app",
            "appLanguageDetail": "Utilisée pour les écrans, menus et boutons de KnotLink.",
            "autoTranslationTitle": "Activer la traduction automatique",
            "translateToTitle": "Traduire les messages en",
            "translateToDetail": "Les messages entrants utiliseront cette langue cible.",
            "saveLanguageSettings": "Enregistrer les réglages de langue",
            "languageSavedOn": "Langue de l’app définie sur %@. La traduction automatique vers %@ est activée.",
            "languageSavedOff": "Langue de l’app définie sur %@. La traduction automatique est désactivée.",
            "thisDevice": "Cet appareil",
            "activeNow": "Actif maintenant",
            "lastActiveJustNow": "Dernière activité : maintenant",
            "current": "Actuel",
            "saveDevicePreferences": "Enregistrer les préférences d’appareil",
            "devicePreferencesSaved": "Préférences d’appareil enregistrées.",
            "selectChat": "Sélectionner une discussion",
            "conversationOpensHere": "Votre conversation s’ouvrira ici.",
            "checkThis": "Regarde ça",
            "updated": "Mis à jour",
            "conversationsCount": "%d conversations",
            "searchChats": "Rechercher des discussions",
            "filter": "Filtre",
            "allChats": "Toutes",
            "groups": "Groupes",
            "bots": "Bots",
            "botChatsWillAppear": "Les discussions avec des bots apparaîtront ici.",
            "noChatsFound": "Aucune discussion trouvée.",
            "createGroup": "Créer un groupe",
            "groupName": "Nom du groupe",
            "groupNamePlaceholder": "Plans du week-end, Équipe de lancement...",
            "chooseMembers": "Choisir les membres",
            "selectedMembersCount": "%d sélectionné(s)",
            "invitePeople": "Inviter des personnes",
            "allContactsInGroup": "Tous les contacts sont déjà dans ce groupe.",
            "contactsSubtitle": "Invitez par téléphone, e-mail ou pseudo.",
            "contactLookupPlaceholder": "Téléphone, e-mail ou @pseudo",
            "incomingRequests": "Demandes reçues",
            "yourContacts": "Vos contacts",
            "noContactsYet": "Aucun contact pour le moment.",
            "message": "Message",
            "sentInvitations": "Invitations envoyées",
            "pending": "En attente",
            "accept": "Accepter",
            "decline": "Refuser",
            "profileSubtitle": "Gérez votre identité publique.",
            "firstName": "Prénom",
            "lastName": "Nom",
            "saveProfile": "Enregistrer le profil",
            "memberSince": "Membre depuis",
            "authSignupSubtitle": "Créez votre compte avec un e-mail ou Google.",
            "authLoginSubtitle": "Connectez-vous avec un e-mail ou Google.",
            "continueWithGoogle": "Continuer avec Google",
            "or": "ou",
            "authenticationMode": "Mode d’authentification",
            "login": "Se connecter",
            "register": "S’inscrire",
            "createAccount": "Créer un compte",
            "password": "Mot de passe",
            "confirmPassword": "Confirmer le mot de passe",
            "back": "Retour",
            "search": "Rechercher",
            "cancel": "Annuler",
            "chatInfo": "Infos de discussion",
            "contactInfo": "Infos du contact",
            "links": "Liens",
            "translateChat": "Traduire",
            "stopTranslation": "Arrêter la traduction",
            "translationEnabledForChat": "La traduction vers %@ est activée.",
            "translationDisabledForChat": "La traduction est désactivée.",
            "clearHistory": "Effacer l’historique",
            "deleteChat": "Supprimer la discussion",
            "attachmentsReady": "Les pièces jointes sont prêtes pour le raccordement au backend.",
            "addAttachment": "Ajouter une pièce jointe",
            "photosAndVideos": "Photos et vidéos",
            "photosAndVideosDetail": "Choisissez des médias dans votre bibliothèque.",
            "files": "Fichiers",
            "filesDetail": "Joindre des documents et des fichiers.",
            "photoAttachment": "Photo",
            "videoAttachment": "Vidéo",
            "fileAttachment": "Fichier",
            "attachmentPrefix": "Pièce jointe",
            "attachmentsAdded": "%d pièce(s) jointe(s) ajoutée(s).",
            "fileImportFailed": "Impossible d’ajouter ce fichier.",
            "removeAttachment": "Retirer la pièce jointe",
            "participants": "%d participants",
            "members": "Membres",
            "linksAndDocs": "Liens et documents",
            "noSharedLinksYet": "Aucun lien partagé pour le moment.",
            "loginSuccessful": "Connexion réussie.",
            "googleSignInFailed": "Échec de la connexion Google.",
            "enterValidEmail": "Saisissez une adresse e-mail valide.",
            "passwordMin": "Le mot de passe doit contenir au moins 8 caractères.",
            "displayNameMin": "Le nom affiché doit contenir au moins 2 caractères.",
            "usernameInvalid": "Le nom d’utilisateur ne peut contenir que des lettres, chiffres et underscores.",
            "enterValidPhone": "Saisissez un numéro de téléphone valide.",
            "passwordsNoMatch": "Les mots de passe ne correspondent pas.",
            "accountCreatedEmailVerification": "Compte créé. La vérification e-mail est prête à être connectée au backend.",
            "messageCannotBeEmpty": "Le message ne peut pas être vide.",
            "messageTooLong": "Le message est trop long. Gardez-le sous 2000 caractères.",
            "enterContactLookup": "Saisissez un téléphone, e-mail ou @pseudo.",
            "noUserFound": "Aucun utilisateur trouvé avec ce téléphone, e-mail ou pseudo.",
            "invitationSent": "Invitation envoyée à %@.",
            "invitationAccepted": "Invitation acceptée. Vous pouvez maintenant discuter avec ce contact.",
            "invitationDeclined": "Invitation refusée.",
            "chatHistoryDeleted": "Historique de discussion supprimé.",
            "chatDeleted": "Discussion supprimée.",
            "profileUpdated": "Profil mis à jour.",
            "enterGroupName": "Saisissez un nom de groupe.",
            "selectAtLeastOneGroupMember": "Sélectionnez au moins un contact pour le groupe.",
            "groupCreated": "Groupe créé.",
            "addedToGroup": "%@ a été ajouté au groupe.",
            "addedPeopleToGroup": "%d personnes ajoutées au groupe."
        ]
    ]
}
